/**
 * Purpose: All git interactions for the merge conflict solver.
 * High-level behavior: Detects conflicting files, applies resolutions,
 *   creates a resolution branch, and commits resolved files.
 * Assumptions: simple-git is installed; working directory is a git repo.
 * Invariants: Never commits to the current branch directly. Validates
 *   resolved content has no conflict markers before writing to disk.
 */

import simpleGit from "simple-git";
import { readFile, writeFile } from "fs/promises";
import { join } from "path";
import { appendFileSync } from "fs";
import type { ConflictingFile } from "./types.js";

const LOG_PATH = "orchestrator.log";

function log(msg: string): void {
    const line = `[${new Date().toISOString()}] [MERGE-GIT] ${msg}\n`;
    process.stdout.write(line);
    try {
        appendFileSync(LOG_PATH, line);
    } catch {
        // Log failures must not crash git operations.
    }
}

/**
 * Detect all files with git conflict markers in the working directory.
 * Returns structured ConflictingFile objects.
 * Returns an empty array if git operations fail — never throws.
 */
export async function detectConflicts(
    projectRoot: string
): Promise<ConflictingFile[]> {
    try {
        const git = simpleGit({ baseDir: projectRoot });
        const status = await git.status();

        const conflictedPaths: string[] = status.conflicted;
        if (conflictedPaths.length === 0) return [];

        log(`Detected ${conflictedPaths.length} conflicting file(s)`);

        const files: ConflictingFile[] = [];
        for (const filePath of conflictedPaths) {
            const fullPath = join(projectRoot, filePath);
            const rawContent = await readFile(fullPath, "utf-8");
            files.push({ path: filePath, rawContent });
            log(`  ${filePath}`);
        }

        return files;
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`detectConflicts failed: ${msg}`);
        return [];
    }
}

/**
 * Write resolved file content to disk.
 * Validates that no conflict markers remain before writing.
 * Throws if conflict markers are still present — this indicates a bug.
 */
export async function applyResolution(
    projectRoot: string,
    filePath: string,
    resolvedContent: string
): Promise<void> {
    const markers = ["<<<<<<<", "=======", ">>>>>>>"];
    const remaining = markers.filter((m) =>
        resolvedContent.includes(m)
    );
    if (remaining.length > 0) {
        throw new Error(
            `Cannot write ${filePath}: conflict markers still present:` +
            ` ${remaining.join(", ")}`
        );
    }

    const fullPath = join(projectRoot, filePath);
    await writeFile(fullPath, resolvedContent, "utf-8");
    log(`Applied resolution to ${filePath}`);
}

/**
 * Create a new branch, stage all resolved files, commit, and push.
 * Branch name: overmind/merge-resolved-{partyCode}-{timestamp}
 * Returns the branch name created.
 */
export async function commitResolutions(
    projectRoot: string,
    partyCode: string,
    resolvedPaths: string[]
): Promise<string> {
    const git = simpleGit({ baseDir: projectRoot });
    const timestamp = Date.now();
    const branchName =
        `overmind/merge-resolved-${partyCode}-${timestamp}`;

    await git.checkoutLocalBranch(branchName);
    log(`Created branch: ${branchName}`);

    await git.add(resolvedPaths);

    const commitMessage =
        `overmind: resolve merge conflicts [${partyCode}]\n\n` +
        `Resolved ${resolvedPaths.length} conflicting file(s) ` +
        `automatically.\n` +
        `Generated by Overmind Merge Conflict Solver Agent.`;

    await git.commit(commitMessage);
    log(`Committed ${resolvedPaths.length} file(s) on ${branchName}`);

    try {
        await git.push("origin", branchName);
        log(`Pushed ${branchName} to origin`);
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`Push failed (PR may not open): ${msg}`);
    }

    return branchName;
}
